require('settings')
require('packer-config')
require('colorschemes-config')
require('nvim-tree-config')
require('mappings')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('lualine-config')
require('barbar-config')
require('treesitter-config')
require('shade-config') -- Seems like it does not work with barbar
require('hydra-config')
require("clipboard")
